# Generated by Django 5.2.4 on 2025-07-08 14:41

import common.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Retailer Categories',
                'db_table': 'retailer_category',
            },
        ),
        migrations.CreateModel(
            name='RetailerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_description', models.TextField(blank=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode')])),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('offers_delivery', models.BooleanField(default=True)),
                ('offers_pickup', models.BooleanField(default=True)),
                ('delivery_radius', models.PositiveIntegerField(default=5)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retailer_profile',
            },
        ),
        migrations.CreateModel(
            name='RetailerOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_operating_hours',
            },
        ),
        migrations.CreateModel(
            name='RetailerCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='retailers.retailercategory')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_category_mapping',
            },
        ),
        migrations.CreateModel(
            name='RetailerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_reviews', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_review',
            },
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['city', 'state'], name='retailer_pr_city_57611d_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['pincode'], name='retailer_pr_pincode_52cdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['is_active', 'is_verified'], name='retailer_pr_is_acti_b4962b_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='retailer_pr_latitud_68a405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retaileroperatinghours',
            unique_together={('retailer', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='retailercategorymapping',
            unique_together={('retailer', 'category')},
        ),
        migrations.AddIndex(
            model_name='retailerreview',
            index=models.Index(fields=['retailer', 'rating'], name='retailer_re_retaile_d40eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerreview',
            index=models.Index(fields=['created_at'], name='retailer_re_created_35cc73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retailerreview',
            unique_together={('retailer', 'customer')},
        ),
    ]
