# Generated by Django 5.2.9 on 2025-12-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerRewardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashback_percentage",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "max_reward_usage_percent",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "max_reward_usage_flat",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_config",
                        to="retailers.retailerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retailer Reward Configuration",
                "verbose_name_plural": "Retailer Reward Configurations",
                "db_table": "retailer_reward_config",
            },
        ),
    ]
