# Generated by Django 5.2.9 on 2025-12-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0002_retailerrewardconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerrewardconfig",
            name="is_referral_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retailerrewardconfig",
            name="min_referral_order_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="retailerrewardconfig",
            name="referee_reward_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="retailerrewardconfig",
            name="referral_reward_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
