# Generated by Django 5.2.9 on 2025-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retailers", "0003_retailerrewardconfig_is_referral_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerprofile",
            name="serviceable_pincodes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
