# Generated by Django 5.2.9 on 2026-01-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0004_retailerprofile_serviceable_pincodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_by', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_customers', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_blacklist',
                'indexes': [models.Index(fields=['retailer', 'customer'], name='retailer_bl_retaile_31e5fc_idx')],
                'unique_together': {('retailer', 'customer')},
            },
        ),
    ]
