# Generated by Django 5.2.9 on 2026-01-11 15:48

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0005_retailerblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path),
        ),
    ]
