# Generated by Django 5.2.9 on 2026-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0006_retailerprofile_upi_id_retailerprofile_upi_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
