# Generated by Django 5.2.9 on 2026-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0007_retailerprofile_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
