# Generated by Django 5.2.9 on 2026-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0008_retailerprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerrewardconfig',
            name='earning_type',
            field=models.CharField(choices=[('percentage', 'Percentage of Order'), ('points_per_amount', 'Points per Order Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='retailerrewardconfig',
            name='loyalty_earning_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='retailerrewardconfig',
            name='loyalty_min_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
