# Generated by Django 5.2.9 on 2026-04-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0009_retailerrewardconfig_earning_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='accepts_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='accepts_upi',
            field=models.BooleanField(default=True),
        ),
    ]
