# Generated by Django 5.2.9 on 2026-04-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0010_retailerprofile_accepts_cod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'supplier',
                'indexes': [models.Index(fields=['retailer', 'company_name'], name='supplier_retaile_5ab206_idx')],
            },
        ),
    ]
