# Generated by Django 5.2.9 on 2026-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0011_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='receipt_footer',
            field=models.TextField(blank=True, help_text='Custom message at the bottom of thermal receipts'),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='show_gst_on_receipt',
            field=models.BooleanField(default=True),
        ),
    ]
