# Generated by Django 5.2.9 on 2026-04-15 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0012_retailerprofile_receipt_footer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text="Retailer's own name for the customer", max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags e.g. VIP, Credit, Regular', max_length=255, null=True)),
                ('customer_type', models.CharField(choices=[('walk_in', 'Walk-in'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='walk_in', max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_mappings', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mappings', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_customer_mapping',
                'indexes': [models.Index(fields=['retailer', 'customer'], name='retailer_cu_retaile_369a81_idx'), models.Index(fields=['customer_type'], name='retailer_cu_custome_965f18_idx')],
                'unique_together': {('retailer', 'customer')},
            },
        ),
    ]
