# Generated by Django 5.2.9 on 2026-05-01 12:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderitem_quantity'),
        ('retailers', '0013_retailercustomermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailercustomermapping',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='retailercustomermapping',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding amount the customer owes to this retailer', max_digits=12),
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Credit Sale'), ('PAYMENT', 'Payment Received'), ('RETURN', 'Sales Return Credit'), ('ADJUSTMENT', 'Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='retailers.retailercustomermapping')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
            ],
            options={
                'db_table': 'customer_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mapping', 'created_at'], name='customer_le_mapping_f32eff_idx'), models.Index(fields=['transaction_type'], name='customer_le_transac_bc1b7e_idx')],
            },
        ),
    ]
