# Generated by Django 5.2.4 on 2026-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0014_retailercustomermapping_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='printer_size',
            field=models.CharField(choices=[('80mm', '80mm (Standard)'), ('58mm', '58mm (Compact)')], default='80mm', help_text='Paper size for thermal receipts', max_length=10),
        ),
    ]
