# Generated by Django 5.2.9 on 2026-09-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_organizations(apps, schema_editor):
    """1:1 Org per existing RetailerProfile (kirana path stays working)."""
    Organization = apps.get_model('retailers', 'Organization')
    RetailerProfile = apps.get_model('retailers', 'RetailerProfile')

    for profile in RetailerProfile.objects.filter(organization__isnull=True).iterator():
        org = Organization.objects.create(
            name=profile.shop_name or f"Organization {profile.pk}",
            owner_id=profile.user_id,
            is_active=True,
        )
        profile.organization_id = org.pk
        profile.save(update_fields=['organization_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0015_retailerprofile_printer_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='When false, new sessions are blocked; history is retained.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant parent. Implicit for existing single-shop tenants (1:1).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='retailers.organization'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='organizatio_owner_i_30e40f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_c0f430_idx'),
        ),
        migrations.RunPython(backfill_organizations, migrations.RunPython.noop),
    ]
