# Generated by Django 5.2.4 on 2026-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0015_retailerprofile_printer_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='print_upi_qr_on_receipt',
            field=models.BooleanField(
                default=False,
                help_text='Print exact-amount UPI QR code on thermal receipts',
            ),
        ),
    ]
