# Generated by Django 5.2.9 on 2026-09-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0019_org_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgModuleFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', models.JSONField(default=dict, help_text='Map of module catalog code -> enabled (bool).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_flags', to='retailers.organization')),
            ],
            options={
                'db_table': 'org_module_flags',
            },
        ),
    ]
