# Generated by Django 5.2.9 on 2026-04-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_batch'),
        ('products', '0026_alter_product_quantity_alter_productbatch_quantity_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='products.purchaseitem'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='orders.orderitem'),
        ),
    ]
