# Generated by Django 5.2.9 on 2026-04-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_purchasereturnitem_purchase_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='return_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
