# Generated by Django 5.2.9 on 2026-05-03 05:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_purchasereturn_return_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
