# Generated by Django 5.2.9 on 2026-01-26 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_payment_mode'),
        ('products', '0011_masterproduct_product_group_product_product_group'),
        ('retailers', '0007_retailerprofile_delivery_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('bxgy', 'Buy X Get Y'), ('percentage', 'Percentage Discount'), ('flat_amount', 'Flat Amount Off'), ('cart_value', 'Cart Value Discount'), ('tiered_price', 'Tiered/Wholesale Price'), ('flat_price', 'Flat Price Sale')], max_length=20)),
                ('value_type', models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Fixed Amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 10 for 10% or 100 for ₹100 off)', max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Max cap for percentage discounts', max_digits=10, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='Buy X', null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, help_text='Get Y', null=True)),
                ('is_cheapest_free', models.BooleanField(default=True, help_text='If mixing items, cheapest is free')),
                ('tiered_min_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = Higher priority')),
                ('is_stackable', models.BooleanField(default=False, help_text='Can be applied with other offers')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('current_redemptions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='offers.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='orders.order')),
            ],
            options={
                'db_table': 'offer_redemption',
            },
        ),
        migrations.CreateModel(
            name='OfferTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('all_products', 'All Products'), ('product', 'Specific Product'), ('category', 'Category'), ('brand', 'Brand')], max_length=20)),
                ('is_excluded', models.BooleanField(default=False, help_text='Set true to exclude this target from the offer')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productbrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='offers.offer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'offer_target',
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['retailer', 'is_active', 'start_date', 'end_date'], name='offer_retaile_ce54dd_idx'),
        ),
        migrations.AddIndex(
            model_name='offerredemption',
            index=models.Index(fields=['offer', 'customer'], name='offer_redem_offer_i_806af4_idx'),
        ),
    ]
