# Generated by Django 5.2.9 on 2026-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='benefit_type',
            field=models.CharField(choices=[('discount', 'Instant Discount'), ('credit_points', 'Loyalty Points (Cashback)')], default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='offerredemption',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Discount/Points value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='offerredemption',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
