# Generated by Django 5.2.9 on 2026-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_benefit_type_offerredemption_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_banners/'),
        ),
    ]
