# Generated by Django 5.2.9 on 2026-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bxgy_strategy',
            field=models.CharField(choices=[('mixed', 'Mix and Match (Any eligible product)'), ('same_product', 'Same Product (Buy X of A, Get Y of A)')], default='mixed', help_text='How items are grouped for Buy X Get Y', max_length=20),
        ),
    ]
