# Generated by Django 5.2.9 on 2026-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_bxgy_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='buy_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Buy X', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='get_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Get Y', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tiered_min_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
