# Generated by Django 5.2.9 on 2026-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offer_buy_quantity_alter_offer_get_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applicable_on',
            field=models.CharField(choices=[('mobile', 'Mobile App Only'), ('pos', 'POS Only'), ('both', 'Both Mobile and POS')], default='both', help_text='Where this offer can be applied', max_length=10),
        ),
    ]
