# Generated by Django 5.2.9 on 2026-09-25 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offerredemption_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, help_text='If set, this offer requires a coupon code to apply', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='eligible_customers',
            field=models.ManyToManyField(blank=True, help_text="Specific customers eligible when target_audience is 'selected'", related_name='exclusive_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If true, shows in customer app available coupons list'),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Customers'), ('first_time', 'First Order Only'), ('selected', 'Specific Customers')], default='all', help_text='Audience eligibility for this coupon/offer', max_length=20),
        ),
        migrations.AddField(
            model_name='offerredemption',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
