# Generated by Django 5.2.9 on 2026-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('shadow', 'Shadow'), ('registered', 'Registered')], default='registered', max_length=20),
        ),
    ]
