# Generated by Django 5.2.9 on 2025-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashback_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Percentage of order total to be driven back as points (e.g., 1.0 = 1%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_reward_usage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Maximum percentage of order total that can be paid using points (e.g., 50.0 = 50%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_reward_usage_flat",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        help_text="Maximum flat amount that can be paid using points per order",
                        max_digits=10,
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Value of 1 point in currency (e.g., 1.0 = ₹1)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Reward Configuration",
                "verbose_name_plural": "Reward Configurations",
                "db_table": "reward_configuration",
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="reward_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
