# Generated by Django 5.2.9 on 2025-12-25 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_rewardconfiguration_customerprofile_reward_points"),
        ("retailers", "0002_retailerrewardconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLoyalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_loyalty",
                        to="retailers.retailerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "customer_loyalty",
            },
        ),
        migrations.DeleteModel(
            name="RewardConfiguration",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="reward_points",
        ),
        migrations.AddIndex(
            model_name="customerloyalty",
            index=models.Index(
                fields=["customer", "retailer"], name="customer_lo_custome_6452e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerloyalty",
            unique_together={("customer", "retailer")},
        ),
    ]
