# Generated by Django 5.2.9 on 2025-12-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customerloyalty_delete_rewardconfiguration_and_more"),
        ("retailers", "0003_retailerrewardconfig_is_referral_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CustomerReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_rewarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="retailers.retailerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "customer_referral",
                "indexes": [
                    models.Index(
                        fields=["retailer", "referee"],
                        name="customer_re_retaile_70a907_idx",
                    ),
                    models.Index(
                        fields=["referrer", "retailer"],
                        name="customer_re_referre_126e9a_idx",
                    ),
                ],
                "unique_together": {("retailer", "referee")},
            },
        ),
    ]
