# Generated by Django 5.2.9 on 2026-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerprofile_referral_code_customerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
