# Generated by Django 5.2.9 on 2026-03-31 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerprofile_average_rating_and_more'),
        ('retailers', '0008_retailerprofile_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('refund', 'Points Refunded'), ('expire', 'Points Expired')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'loyalty_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'retailer', 'transaction_type'], name='loyalty_tra_custome_d25bfd_idx'), models.Index(fields=['expiry_date', 'is_expired'], name='loyalty_tra_expiry__15076b_idx')],
            },
        ),
    ]
