# Generated by Django 5.2.4 on 2025-07-08 14:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('retailers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_carts', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add Item'), ('remove', 'Remove Item'), ('update', 'Update Quantity'), ('clear', 'Clear Cart'), ('checkout', 'Checkout')], max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'cart_history',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'cart_session',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', 'retailer'], name='cart_custome_8796b8_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='cart_updated_d0d143_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'retailer')},
        ),
        migrations.AddIndex(
            model_name='carthistory',
            index=models.Index(fields=['customer', 'created_at'], name='cart_histor_custome_4e04aa_idx'),
        ),
        migrations.AddIndex(
            model_name='carthistory',
            index=models.Index(fields=['retailer', 'created_at'], name='cart_histor_retaile_c6b05d_idx'),
        ),
        migrations.AddIndex(
            model_name='carthistory',
            index=models.Index(fields=['action'], name='cart_histor_action_285633_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='cart_item_cart_id_1d10c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_item_product_d993b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['session_key'], name='cart_sessio_session_aac29f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartsession',
            index=models.Index(fields=['updated_at'], name='cart_sessio_updated_4b2026_idx'),
        ),
    ]
