# Generated by Django 5.2.9 on 2026-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_carthistory_quantity_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
