# Generated by Django 5.2.9 on 2025-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("waiting_for_customer_approval", "Waiting for Customer Approval"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="new_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="old_status",
            field=models.CharField(max_length=50),
        ),
    ]
