# Generated by Django 5.2.9 on 2025-12-25 17:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_status_alter_orderstatuslog_new_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_from_points",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="points_earned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="points_redeemed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
