# Generated by Django 5.2.9 on 2026-01-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderchatmessage'),
        ('retailers', '0005_retailerblacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_rating', to='orders.order')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_rating',
                'unique_together': {('order', 'retailer')},
            },
        ),
    ]
