# Generated by Django 5.2.9 on 2026-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_retailerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='app', max_length=50),
        ),
    ]
