# Generated by Django 5.2.9 on 2026-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('cash_pickup', 'Cash on Pickup'), ('upi', 'UPI')], max_length=20),
        ),
    ]
