# Generated by Django 5.2.9 on 2026-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
