# Generated by Django 5.2.9 on 2026-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_estimated_ready_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_processing_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
