# Generated by Django 5.2.9 on 2026-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
