# Generated by Django 5.2.9 on 2026-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending_payment', max_length=50),
        ),
    ]
