# Generated by Django 5.2.9 on 2026-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_is_payment_locked_order_payment_edit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('app', 'Online App'), ('pos', 'POS (Walk-in)')], default='app', max_length=50),
        ),
    ]
