# Generated by Django 5.2.9 on 2026-04-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_guest_mobile_order_guest_name_and_more'),
        ('products', '0025_product_has_batches_productbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbatch'),
        ),
    ]
