# Generated by Django 5.2.9 on 2025-12-27 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="MasterProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_products",
                        to="products.productbrand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_products",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "master_product",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="master_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retailer_products",
                to="products.masterproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="masterproduct",
            index=models.Index(fields=["name"], name="master_prod_name_fc6bdd_idx"),
        ),
        migrations.AddIndex(
            model_name="masterproduct",
            index=models.Index(
                fields=["barcode"], name="master_prod_barcode_7f2134_idx"
            ),
        ),
    ]
