# Generated by Django 5.2.9 on 2025-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_product_barcode_masterproduct_product_master_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="masterproduct",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum Retail Price",
                max_digits=10,
                null=True,
            ),
        ),
    ]
