# Generated by Django 5.2.9 on 2026-01-02 19:06

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_masterproduct_mrp"),
        ("retailers", "0004_retailerprofile_serviceable_pincodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUploadSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("discarded", "Discarded"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="retailers.retailerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "product_upload_session",
            },
        ),
        migrations.CreateModel(
            name="UploadSessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.generate_upload_path,
                    ),
                ),
                ("product_details", models.JSONField(blank=True, default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.productuploadsession",
                    ),
                ),
            ],
            options={
                "db_table": "upload_session_item",
            },
        ),
        migrations.AddIndex(
            model_name="productuploadsession",
            index=models.Index(
                fields=["retailer", "status"], name="product_upl_retaile_dc5d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsessionitem",
            index=models.Index(
                fields=["session", "barcode"], name="upload_sess_session_b4ab9e_idx"
            ),
        ),
    ]
