# Generated by Django 5.2.9 on 2026-01-03 08:43

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productuploadsession_uploadsessionitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.generate_upload_path,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.masterproduct",
                    ),
                ),
            ],
            options={
                "db_table": "master_product_image",
            },
        ),
    ]
