# Generated by Django 6.0 on 2026-01-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_masterproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterproduct',
            name='attributes',
        ),
    ]
