# Generated by Django 6.0 on 2026-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_masterproduct_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
