# Generated by Django 6.0 on 2026-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_masterproduct_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
