# Generated by Django 5.2.9 on 2026-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadsession',
            name='name',
            field=models.CharField(blank=True, default='Untitled Session', max_length=255),
        ),
    ]
