# Generated by Django 5.2.9 on 2026-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productuploadsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='product_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
