# Generated by Django 5.2.9 on 2026-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_gin_index'),
        ('retailers', '0007_retailerprofile_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_seasonal'], name='product_is_seas_99c8da_idx'),
        ),
    ]
