# Generated by Django 5.2.9 on 2026-02-26 06:52

from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_seasonal_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
