# Generated by Django 5.2.9 on 2026-02-26 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_enable_trigram_extension'),
        ('retailers', '0007_retailerprofile_delivery_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_telemetry', to='retailers.retailerprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_telemetry',
                'indexes': [models.Index(fields=['query'], name='search_tele_query_3c9c68_idx'), models.Index(fields=['created_at'], name='search_tele_created_638e62_idx'), models.Index(fields=['result_count'], name='search_tele_result__8b8aa3_idx')],
            },
        ),
    ]
