# Generated by Django 5.2.9 on 2026-03-20 05:41

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_searchtelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
