# Generated by Django 5.2.9 on 2026-03-20 06:43

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productcategory_image_productcategory_image_url'),
        ('retailers', '0008_retailerprofile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='image_url',
        ),
        migrations.CreateModel(
            name='RetailerProductCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.utils.generate_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_images', to='products.productcategory')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_category_images', to='retailers.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_product_category_image',
                'indexes': [models.Index(fields=['retailer'], name='retailer_pr_retaile_a1ac2c_idx'), models.Index(fields=['category'], name='retailer_pr_categor_0dfcc9_idx')],
                'unique_together': {('retailer', 'category')},
            },
        ),
    ]
