# Generated by Django 5.2.9 on 2026-03-20 10:54

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productcategory_image_and_more'),
        ('retailers', '0008_retailerprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerProductCategorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_settings', to='products.productcategory')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_settings', to='retailers.retailerprofile')),
            ],
            options={
                'verbose_name': 'Retailer Category Setting',
                'verbose_name_plural': 'Retailer Category Settings',
                'db_table': 'retailer_product_category_settings',
                'unique_together': {('retailer', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='RetailerProductCategoryImage',
        ),
    ]
