# Generated by Django 5.2.9 on 2026-03-20 14:51

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_retailerproductcategorysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path),
        ),
        migrations.DeleteModel(
            name='RetailerProductCategorySettings',
        ),
    ]
