# Generated by Django 5.2.9 on 2026-03-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productcategory_image_and_more'),
        ('retailers', '0008_retailerprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='retailers.retailerprofile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('retailer', 'name')},
        ),
    ]
