# Generated by Django 5.2.9 on 2026-04-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_purchase_price_purchaseinvoice_purchaseitem_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_vector_idx',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='reference_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='products.purchaseinvoice'),
        ),
    ]
