# Generated by Django 5.2.9 on 2026-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_has_batches_productbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='new_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinventorylog',
            name='previous_quantity',
            field=models.IntegerField(),
        ),
    ]
