# Generated by Django 5.2.9 on 2026-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_quantity_alter_productbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='additional_barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
