# Generated by Django 5.2.9 on 2026-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_quantity_alter_productbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
