# Generated by Django 5.2.9 on 2026-05-24 12:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weight ratio of child weight relative to parent bulk SKU (e.g., 0.10 for 5kg from 50kg)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_parent_bulk',
            field=models.BooleanField(default=False, help_text='Is this the master parent bulk product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_bulk_product',
            field=models.ForeignKey(blank=True, help_text='Reference to the parent bulk product keeping master inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fractional_children', to='products.product'),
        ),
    ]
