# Generated by Django 5.2.9 on 2026-08-19 17:40

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_conversion_factor_product_is_parent_bulk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.generate_upload_path),
        ),
    ]
