# Generated by Django 5.2.9 on 2026-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_purchaseinvoice_bill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventorylog',
            name='log_type',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('reconciled', 'Reconciled')], max_length=20),
        ),
    ]
